# Generated by Django 5.0.2 on 2024-02-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sports',
        ),
        migrations.AddField(
            model_name='college',
            name='sports',
            field=models.ManyToManyField(related_name='colleges', through='main.Team', to='main.sport'),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sport'),
        ),
    ]
